---
version: 2
jobs:
  build:
    branches:
      only:
        - content
    working_directory: /var/app
    docker:
      - image: node:latest
    steps:
      - run: |
          curl -sSL https://github.com/spf13/hugo/releases/download/v0.19/hugo_0.19_Linux-64bit.tar.gz \
          | tar xz -C /usr/local/bin
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: yarn install --force
      - run: git config --global user.name "circleci"
      - run: git config --global user.email "circleci@circleci.com"
      - run: make deploy
...
