baseurl = "https://mijime.github.io/"
languageCode = "ja"
title = "My snippets"
HasCJKLanguage = true

[params]
  keywords = [ "mijime" ]
  description = "何かをかく"
  css = "layout-reverse"

[params.googleAnalytics]
  UA = "UA-46554348-4"
  SiteVerification = "7gVj5rzyozu0vYcQMLhIGr4g-WWyJn4R22RgeYqQdS0"

[[menu.main]]
  name = "Posts"
  url = "/posts"

[[menu.main]]
  name = "Slides"
  url = "/slides"

[[menu.main]]
  name = "Tags"
  url = "/tags"
