baseurl = "/"
languageCode = "ja"
title = "My snippets"
HasCJKLanguage = true

[params]
  description = "何かをかく"
  css = "layout-reverse"

[params.googleAnalytics]
  UA = "UA-46554348-4"

[[menu.main]]
  name = "Posts"
  url = "/posts"

[[menu.main]]
  name = "Slides"
  url = "/slides"

[[menu.main]]
  name = "Tags"
  url = "/tags"
