[tools]
node = "22"
lefthook = "latest"
"npm:pnpm" = "latest"

[tasks."format:pnpm"]
run = "pnpm run format"

[tasks."check:pnpm"]
run = "pnpm run check"

[tasks."test:pnpm"]
run = "pnpm -r run test"

[tasks.format]
depends = ["format:pnpm"]

[tasks.check]
depends = ["check:pnpm"]

[tasks.test]
depends = ["test:pnpm"]

[tasks.ci]
depends = ["format", "check", "test"]

[tasks.build]
run = "pnpm run build"
depends = ["ci"]
