[tools]
node = "lts"
lefthook = "latest"
bun = "latest"

[tasks."format:bun"]
run = "bun run format"
sources = ["*/*/src/**/*.{ts,tsx,astro}"]

[tasks."check:bun"]
run = "bun run check"
sources = ["*/*/src/**/*.{ts,tsx,astro}"]

[tasks."test:bun"]
run = "bun test"
sources = ["*/*/src/**/*.{ts,tsx,astro}"]

[tasks.format]
depends = ["format:bun"]

[tasks.check]
depends = ["check:bun"]

[tasks.test]
depends = ["test:bun"]

[tasks.ci]
depends = ["format", "check", "test"]

[tasks.build]
run = "bun run build"
depends = ["ci"]
