[tools]
node = "lts"
lefthook = "latest"
bun = "latest"

[tasks."format:oxfmt"]
run = "bun run --filter '*' format:oxfmt"
sources = ["*/*/src/**/*.{ts,tsx}"]

[tasks."check:oxlint"]
run = "bun run --filter '*' check:oxlint"
sources = ["*/*/src/**/*.{ts,tsx}"]

[tasks."check:tsgo"]
run = "bun run --filter '*' check:tsgo"
sources = ["*/*/src/**/*.{ts,tsx}"]

[tasks."test:bun"]
run = "bun test"
sources = ["*/*/src/**/*.{ts,tsx}"]

[tasks.format]
depends = ["format:oxfmt"]

[tasks.check]
depends = ["check:oxlint", "check:tsgo"]

[tasks.test]
depends = ["test:bun"]

[tasks.ci]
depends = ["format", "check", "test"]
