---
version: 2
jobs:
  build:
    branches:
      only:
        - content
    working_directory: /var/app
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: yarn install --force
      - run: git config --global user.name "circleci"
      - run: git config --global user.email "circleci@circleci.com"
      - run: make assets/hugo
      - run: make deploy
...
