---
name: Lint markdown

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm install && npm prune
      - run: npm run lint:md
